### ISSUE TITLE
Autograd for complex matrix multiplication in Pytorch ?

### ISSUE THREAD

**Issue by RobinhoodKi** [fkodom/fft-conv-pytorch#5]
Thanks a lot for sharing your code. It helps me a lot ! I have a question about complex matrix multiplication. I notice that you made some comments on this part saying that "This is fairly hacky but necessary for PyTorch 1.7.0, because Autograd is not enabled for complex matrix operations yet."  But when I using Pytorch 1.7.0 , I just use 'c = a * b ' directly. It seems that autograd works quite well ? I'm not sure now... Would you like to do some experiments to double check it ? Thanks a lot !

**Comment by fkodom** [comment]
Sorry for the delay here..

Did you do matrix multiplication (`c = a.matmul(b)` or `c = a @ b`) or direct multiplication (`c = a * b`)?  From your comment, it looks like direct multiplication.  Direct multiplication may already have Autograd support in v1.7.0.

**Comment by RobinhoodKi** [comment]
Thanks a lot for your reply ! I'm not quite familiar with fft-conv. I'd appreciate it if you can give me some advice. Here's my code. If  I have two image of signal, whose shapes are `[1, H0, W0]` ,  and two image of kernel whose shapes are `[1, H1,W1]` , `H1<H0` and `W1 < W0`.  I want to do convolution independently in a batch. Like signal 1 conv with kernel 1 and signal 2 conv with kernel 2.  My question is that after doing FFT, can I use `(c = a * b)` directly or should I use `c = a @ b` instead. Actually, I dont understand why we need to use matrix multiplication? According to convolution theory, I think we should. use dot multiplication. Thanks a lot again for your sharing !  
<img width="1035" alt="截屏2021-01-22上午10 43 31" src="https://user-images.githubusercontent.com/48984155/105438813-ace1cf00-5c9e-11eb-892d-9afe28b027a3.png">

**Comment by fkodom** [comment]
Ah, sorry I think I misunderstood your original question.  You're exactly right -- you should use direct multiplication after performing the FFT.  But if you try and track gradients through your function, I believe you'll get an error in PyTorch 1.7.0.

Example:
```
layer = FFTConv1d(4, 4, 3)
x = torch.randn(2, 4, 128)
y = layer(x)
loss = y.mean()
loss.backward()

# RuntimeError: _unsafe_view does not support automatic differentiation for outputs with complex dtype.
```

^^ That's where my "hacky" comment came from:
```
# (fft_conv.py - lines 24:27)
# Compute the real and imaginary parts independently, then manually insert them
# into the output Tensor.  This is fairly hacky but necessary for PyTorch 1.7.0,
# because Autograd is not enabled for complex matrix operations yet.  Not exactly
# idiomatic PyTorch code, but it should work for all future versions (>= 1.7.0).
```

You likely won't see this error with the `fft_conv` method, because gradients are not tracked by default!  But `nn.Module` layers like `FFTConv1d` automatically track gradients, and an error gets thrown when `loss.backward()` is called.

Also, if the signal/kernel has more than 1 channel, you'll need to use the `complex_matmul` method in `fft_conv.py`. (Because PyTorch convolutions actually perform matrix multiplication over the channel dimension.)  But from your question, it sounds like you're only using 1 channel.
